spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: '*'
    schema:
      printer:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 100